import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import CartModalWrapper from "@/features/shared/UI/CartModalWrapper";
import Header from "@/features/shared/UI/Header";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${poppins.variable}  antialiased font-poppins`}
      >
        <div className="w-[1980px] m-auto px-[130px]">
        <Header />
        <div className="mt-18">
        <CartModalWrapper/>
          {children}
</div>
</div>
      </body>
    </html>
  );
}
